### ISSUE TITLE
POIs are not loading due to wrong overpass uri

### ISSUE THREAD

**Issue by ghost** [marczoutendijk/openpoimap#13]
I just came across openpoimap and I found that the POIs are not loading at all. When I looked at the network calls with the Chrome developer tools, I found that the page calls overpass like this:

`http://overpass-api.de/api/interpreter/http://overpass-api.de/api/interpreter/?data=(node[tourism=chalet](bbox);way[tourism=chalet](bbox);rel[tourism=chalet](bbox););(._;%3E;);out%20center;&bbox=-8.2352790898347,37.636953943645,-8.2174048482753,37.666548537167`

So the POIs not loading is probably due to the messed up schema and host in the url.

**Comment by marczoutendijk** [comment]
Hi Georg,


> Op 19 jun. 2020, om 19:25 heeft Georg von der Howen <notifications@github.com> het volgende geschreven:
> 
> 
> I just came across openpoimap and I found that the POIs are not loading at all. When I looked at the network calls with the Chrome developer tools, I found that the page calls overpass like this:
> 
> http://overpass-api.de/api/interpreter/http://overpass-api.de/api/interpreter/?data=(node[tourism=chalet](bbox);way[tourism=chalet](bbox);rel[tourism=chalet](bbox););(._;%3E;);out%20center;&bbox=-8.2352790898347,37.636953943645,-8.2174048482753,37.666548537167
> 
> So the POIs not loading is probably due to the messed up schema and host in the url.
> 
> 

I cannot replicate the problem you describe.
With this link:
http://openpoimap.org/?map=hotels&zoom=17&lat=52.48884&lon=6.3803&layers=B00FFFTFFFFFFF <http://openpoimap.org/?map=hotels&zoom=17&lat=52.48884&lon=6.3803&layers=B00FFFTFFFFFFF>
I see all the tourism=chalet tags where they are supposed to be.

Can you check my link?
Can you point me also to the location on the map where you have tried it?

All the best,
Marc.

**Comment by ghost** [comment]
Hi Marc,

this is strange. Your link is working for me as well, but I can reproduce the issue here:

https://openpoimap.org/?map=amenity&zoom=14&lat=37.86894&lon=-8.143&layers=B00FFFFFFTFTTTTFFFFFFFFFFFFFFFFFF

Best regards
Georg

**Comment by marczoutendijk** [comment]
Hi Georg,

> this is strange. Your link is working for me as well, but I can reproduce the issue here:
> 
> https://openpoimap.org/?map=amenity&zoom=14&lat=37.86894&lon=-8.143&layers=B00FFFFFFTFTTTTFFFFFFFFFFFFFFFFFF <https://openpoimap.org/?map=amenity&zoom=14&lat=37.86894&lon=-8.143&layers=B00FFFFFFTFTTTTFFFFFFFFFFFFFFFFFF>
> Best regards
> Georg
> 

I see that you are calling openpoimap with https:// but it SHOULD be called with http:// like this:

http://openpoimap.org/?map=amenity&zoom=14&lat=37.87706&lon=-8.16475&layers=B00FFFFFFTFTTTTFFFFFFFFFFFFFFFFFF <http://openpoimap.org/?map=amenity&zoom=14&lat=37.87706&lon=-8.16475&layers=B00FFFFFFTFTTTTFFFFFFFFFFFFFFFFFF>

Curently there is no https:// call possible for openpoimap.


Regards,
Marc.

**Comment by ghost** [comment]
Ah, thanks. It must be Chrome defaulting to https if you don't specify a schema explicitly, as SSL is available, although with an invalid certificate. Thanks!
