### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cdauth** [marczoutendijk/openpoimap#14]
I am planning to implement a function similar to OpenPOIMap into [FacilMap](https://github.com/facilmap/facilmap). While I haven’t decided the details yet, I think that the source code of OpenPOIMap would be a good inspiration, and the [list of amenities](https://github.com/marczoutendijk/openpoimap/blob/master/js_source/opm.js#L1438) is a good collection of POI types.

I am thus wondering under which license the source code of OpenPOIMap is published. I was not able to find any details about this. Can I reuse parts of the source code in my project?

**Comment by marczoutendijk** [comment]
Hi Candid,


> You asked:
> 
> I am planning to implement a function similar to OpenPOIMap into FacilMap <https://github.com/facilmap/facilmap>. While I haven’t decided the details yet, I think that the source code of OpenPOIMap would be a good inspiration, and the list of amenities <https://github.com/marczoutendijk/openpoimap/blob/master/js_source/opm.js#L1438> is a good collection of POI types.
> I am thus wondering under which license the source code of OpenPOIMap is published. I was not able to find any details about this. Can I reuse parts of the source code in my project?
> 

You can use the code without any restrictions, but a reference (somewhere in your source code) to the parts you copied or used are welcome!

Please let me know how you proceed!

Best regards,
Marc.

**Comment by cdauth** [comment]
Hey Marc,

Thanks for your kindness!

I have implemented a POI feature into FacilMap now. I took the list of POI types from OpenPoiMap (with some minor modifications) and have left a comment in the [source code](https://github.com/FacilMap/facilmap/blob/master/leaflet/src/overpass/overpass-presets.ts#L12).

If you are interested to see what I have implemented, use the POI tab on [FacilMap](https://facilmap.org/), see the [user guide](https://docs.facilmap.org/users/pois/) and the [developer documentation](https://docs.facilmap.org/developers/leaflet/overpass.html#use-a-preset).

**Comment by not-my-profile** [comment]
@marczoutendijk I think it would be a good idea to add a `LICENSE.txt` file or something like that with an actual license, so that people don't have to search GitHub issues to find out under which terms this code may be used.

If you don't want to enforce any restrictions and only want to be credited in the source code, the MIT license should serve you well: https://choosealicense.com/licenses/mit/
