### ISSUE TITLE
HTTPS links

### ISSUE THREAD

**Issue by bonanza123** [marczoutendijk/openpoimap#6]
There is a problem due to the use of "HTTPS everywhere" extension which comes with a profile for openstreetmap.org. 
The problem is that this plugin enforce HTTPS on all links to openstreetmap.org which seems to fail on this awesome website.
It look like changing the openstreetmap.org links (and maybe others too?) solves that problem.

**Comment by marczoutendijk** [comment]
Thanks for that!
I'll check the code to see what can be solved.
OpenPoiMap uses a library of javascriptcode that is beyond my control...
